# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-19 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsLearning', '0002_auto_20180719_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
