# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-20 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsLearning', '0006_auto_20180720_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='publish_data',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postmodel',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
