# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-20 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsLearning', '0007_auto_20180720_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(max_length=240, unique=True),
        ),
    ]
