# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-20 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsLearning', '0008_auto_20180720_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='publish_data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
