# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-20 13:53
from __future__ import unicode_literals

import ModelsLearning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsLearning', '0009_auto_20180720_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='author_email',
            field=models.CharField(blank=True, max_length=240, null=True, validators=[ModelsLearning.models.validate_author_email]),
        ),
    ]
