# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-22 12:14
from __future__ import unicode_literals

import ModelsLearning.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsLearning', '0010_postmodel_author_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='author_email',
            field=models.EmailField(blank=True, max_length=240, null=True, validators=[ModelsLearning.validators.validate_author_email]),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(max_length=240, unique=True, verbose_name='Post title'),
        ),
    ]
